app = "afkbot"
primary_region = "arn"

[processes]
  app = "node --optimize-for-size --max-old-space-size=512 index.js"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1024mb"
  cpus = 1
  cpu_kind = "shared"

[swap]
  size_mb = 512
